CREATE TABLE SMARTPHONES (
    DEVICE_ID TEXT,
    DEVICE_BRAND TEXT,
    DEVICE_POPULARITY INTEGER,
    DEVICE_PRICE_RANGE TEXT
);

INSERT INTO SMARTPHONES (DEVICE_ID, DEVICE_BRAND, DEVICE_POPULARITY, DEVICE_PRICE_RANGE) VALUES
    ('1', 'APPLE', 1, 'FROM 50K TO 1LAKH'),
    ('2', 'SAMSUNG', 2, 'FROM 12K TO 1LAKH'),
    ('3', 'BBK ELECTRONICS (OPPO, VIVO, etc.)', 3, 'FROM 10K TO 40K'),
    ('4', 'XIAOMI', 4, 'FROM 8K TO 30K'),
    ('5', 'OTHER ELECTRONICS', 5, 'FROM 6K TO 20K');

SELECT COUNT(DEVICE_ID) AS Device_Count
FROM SMARTPHONES;
