CREATE TABLE PRODUCTS (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    CATEGORY_NAME TEXT,
    QUANTITY_REQUIRED INTEGER,
    COST INTEGER
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_NAME, QUANTITY_REQUIRED, COST)VALUES
    ('1', 'APPLE WATCH SERIES 9', 'SMARTWATCH', 5, 95000),
    ('2', 'IPHONE 16 PROMAX', 'SMARTPHONE', 15, 175000),
    ('3', 'MACBOOK', 'LAPTOP', 8, 150000),
    ('4', 'SAMSUNG SMART MONITOR M8', 'MONITOR_TV', 6, 55000),
    ('5', 'IPAD PRO WITH PENCIL', 'TABLET', 4, 125000);

SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;

SELECT AVG(COST) AS Average_Cost
FROM PRODUCTS;

SELECT SUM(COST) AS Total_Cost
FROM PRODUCTS;
